name: Deploy App to Server

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/terhandle-api:latest

  deploy-prod:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Connect to server using SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop terhandle
            docker rm terhandle
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/terhandle-api:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/terhandle-api:latest
            docker run -d -p 8080:8080 -e SERVERPORT=${{ secrets.SERVERPORT }} -e DBUSER=${{ secrets.DBUSER }} -e DBPASS=${{ secrets.DBPASS }} -e DBHOST=${{ secrets.DBHOST }} -e DBPORT=${{ secrets.DBPORT }} -e DBNAME=${{ secrets.DBNAME }} -e JWT_SECRET=${{ secrets.JWT_SECRET }} -e API_KEY=${{ secrets.API_KEY }} -e BUCKET_NAME=${{ secrets.BUCKET_NAME }} -e ACCOUNT_ID=${{ secrets.ACCOUNT_ID }} -e ACCESSKEY_ID=${{ secrets.ACCESSKEY_ID }} -e SECRET_ACCES_KEY=${{ secrets.SECRET_ACCES_KEY }} -e OPEN_API_KEY=${{ secrets.OPEN_API_KEY }} --name terhandle ${{ secrets.DOCKERHUB_USERNAME }}/terhandle-api:latest